spring:
  application:
    name: mentoai-api
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: teste
    password: a123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
